import streamlit as st
import pandas as pd
import os

def PlotFFT(key="plot-fft"):
    """
    Independent component to plot FFT extraction results from a saved CSV file.
    """
    st.markdown("### Interactive FFT Plotter")
    
    input_path = st.text_input(
        "Input FFT CSV File Path",
        placeholder="Enter path to your extracted .csv file (e.g., subject_fft.csv)",
        help="Paste the absolute path to the CSV file generated by the 'FFT Analysis' tab.",
        key=f"{key}-input"
    )
    
    # Clean up accidental quotes from copy-pasting paths
    if input_path:
        input_path = input_path.strip('\"\'')
        
    if input_path:
        if not os.path.exists(input_path):
            st.error("Input file does not exist. Please check the path.")
        elif not input_path.lower().endswith('.csv'):
            st.error("Input file must be a .csv file.")
        else:
            try:
                # Load CSV
                df = pd.read_csv(input_path)
                
                # Assume 'Condition' is a column if it was saved from the index
                if 'Condition' in df.columns:
                    df_plot = df.set_index('Condition')
                elif len(df.columns) > 0:
                    # Fallback to the first column as the index (usually the previous index name)
                    df_plot = df.set_index(df.columns[0])
                else:
                    df_plot = df
                
                # Exclude non-numeric data like 'Subject' from the plot metrics
                df_numeric = df_plot.select_dtypes(include=['number'])
                
                available_bands = df_numeric.columns.tolist()
                default_bands = ["delta_ant", "delta_post"]
                default_bands = [b for b in default_bands if b in available_bands]
                
                # Fallback if the requested default bands aren't present
                if not default_bands and available_bands:
                    default_bands = available_bands[:min(2, len(available_bands))]
                    
                selected_bands = st.multiselect(
                    "Select Frequency Bands to Display", 
                    options=available_bands, 
                    default=default_bands, 
                    key=f"{key}-select-bands"
                )
                
                if selected_bands:
                    st.bar_chart(df_numeric[selected_bands], stack=False)
                else:
                    st.info("Select at least one band to display the plot.")
                    
            except Exception as e:
                st.error(f"Error reading or plotting CSV: {e}")
