import streamlit as st
import pandas as pd
import os

def PlotConnectivity(key="plot-connectivity"):
    """
    Independent component to plot Connectivity extraction results from a saved CSV file.
    """
    st.markdown("### Interactive Connectivity Plotter")
    
    input_path = st.text_input(
        "Input Connectivity CSV File Path",
        placeholder="Enter path to your extracted .csv file (e.g., subject_connectivity.csv)",
        help="Paste the absolute path to the CSV file generated by the 'Connectivity Analysis' tab.",
        key=f"{key}-input"
    )
    
    # Clean up accidental quotes from copy-pasting paths
    if input_path:
        input_path = input_path.strip('\"\'')
        
    if input_path:
        if not os.path.exists(input_path):
            st.error("Input file does not exist. Please check the path.")
        elif not input_path.lower().endswith('.csv'):
            st.error("Input file must be a .csv file.")
        else:
            try:
                # Load CSV
                df = pd.read_csv(input_path)
                
                # Combine Condition and FreqBand for index if both exist
                if 'Condition' in df.columns and 'FreqBand' in df.columns:
                    df['PlotLabel'] = df['Condition'].astype(str) + ' - ' + df['FreqBand'].astype(str)
                    df_plot = df.set_index('PlotLabel')
                elif 'Condition' in df.columns:
                    df_plot = df.set_index('Condition')
                elif len(df.columns) > 0:
                    df_plot = df.set_index(df.columns[0])
                else:
                    df_plot = df
                
                # Exclude non-numeric data like 'Subject' from the plot metrics
                df_numeric = df_plot.select_dtypes(include=['number'])
                
                available_metrics = df_numeric.columns.tolist()
                default_metrics = ["Connectivity", "ShortDistQ1", "MidDistQ1Q3", "LongDistQ3"]
                default_metrics = [m for m in default_metrics if m in available_metrics]
                
                if not default_metrics and available_metrics:
                    default_metrics = available_metrics[:min(3, len(available_metrics))]
                    
                selected_metrics = st.multiselect(
                    "Select Distance Metrics to Display", 
                    options=available_metrics, 
                    default=default_metrics, 
                    key=f"{key}-select-metrics"
                )
                
                if selected_metrics:
                    st.bar_chart(df_numeric[selected_metrics], stack=False, height=600)
                else:
                    st.info("Select at least one metric to display the plot.")
                    
            except Exception as e:
                st.error(f"Error reading or plotting CSV: {e}")
